### PR TITLE
added neu-pink

### PR DESCRIPTION
**Pull request by lovevictoria2020**
Hi!

I added a neumorphic pink theme for issue #36! 

Let me know if you can see it, and if there's anything I need to change.

Thank you!

### CODE REVIEW

**Comment by matteobruni** [comment]
The theme is not working, please run `yarn start` and go to <http://localhost:3030> to test it

**Review by matteobruni — CHANGES_REQUESTED** [review]
The theme is not working, please run `yarn start` and go to <http://localhost:3030> to test it

**Comment by lovevictoria2020** [comment]
Hi!

Thanks so much for letting me know! I ran yarn start, and it didn't find any errors. Not sure why it isn't showing up. :(

**Comment by matteobruni** [comment]
The first parameter of the create theme mixin in `scss` file must match the `addTheme` parameter. If a `neu` theme is created the `neu-` prefix is added automatically

**Comment by lovevictoria2020** [comment]
> The first parameter of the create theme mixin in `scss` file must match the `addTheme` parameter. If a `neu` theme is created the `neu-` prefix is added automatically

Thanks so much! I was able to fix it! Let me know what you think.

**Review by matteobruni — CHANGES_REQUESTED** [review]
The white text color is too light for the pink background and I found it disturbing for my eyes. I tested black and is more readable, but if you prefer another color you can try it.

**Comment by lovevictoria2020** [comment]
Changed it to black! Thank you!

**Review by matteobruni — APPROVED** [review]

**Pull request merged**
